### ISSUE TITLE
NuGet config causes project not to build

### ISSUE THREAD

**Issue by jasonjoh** [microsoftgraph/aspnet-connect-rest-sample#10]
On a default installation of Visual Studio and NuGet, packages are downloaded to the CxCache folder. However, the csproj file in this repository references packages in a `..\packages` folder. If you try to build this on a machine where you haven't redirected NuGet packages, you'll get an error:

`This project references NuGet package(s) that are missing on this computer. Use NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is ..\packages\Microsoft.Net.Compilers.1.0.0\build\Microsoft.Net.Compilers.props.`

You can fix this by adding a Nuget.config file in the root that will ensure that for this solution packages are always downloaded into the `..\packages` directory.

**Comment by DianeD** [comment]
Thanks Jason! I wasn't able to repro this on a clean machine, so renamed one of my packages to simulate. I removed the EnsureNuGetPackageBuildImports target in the csproj file, which I read is another way to fix.
