### ISSUE TITLE
Getting Files returns empty list

### ISSUE THREAD

**Issue by tbird321** [microsoftgraph/aspnet-connect-rest-sample#14]
I added a method to get the files from the root - and it returns an empty list.  The same call in the Microsoft Graph Connect example site returns the full list of files.

public async Task<string> GetFilesList(string accessToken)
        {
            string result = string.Empty;
            string endpoint = "https://graph.microsoft.com/v1.0/me/drive/root/children";
            string queryParameter = "";
            using (var client = new HttpClient())
            {
                using (var request = new HttpRequestMessage(HttpMethod.Get, endpoint + queryParameter))
                {
                    request.Headers.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
                    request.Headers.Authorization = new AuthenticationHeaderValue("Bearer", accessToken);

                    // This header has been added to identify our sample in the Microsoft Graph service. If extracting this code for your project please remove.
                    request.Headers.Add("SampleID", "aspnet-connect-rest-sample");
                    using (HttpResponseMessage response = await client.SendAsync(request))
                    {
                        if (response.StatusCode == HttpStatusCode.OK)
                        {
                            result = await response.Content.ReadAsStringAsync();
                        }
                        return result;
                    }
                }
            }
        }

**Comment by tbird321** [comment]
I resolved this.
I needed to make sure I added the permissions in the api resource requests for files.
I also needed to add this key to the web.config
key="ida:GraphScopes" value="User.Read Mail.Send Files.ReadWrite.All Files.ReadWrite.AppFolder Files.Read"
So that I had sufficient permissions to read the files

**Comment by DianeD** [comment]
Thanks for the update, @tbird321 ! BTW, for that particular GET files request you should only need to specify Files.Read.

**Comment by Masood10** [comment]
I am trying to read all my planner tasks. I have also added permissions on web config and application registration portal but I am getting 403 forbidden error. Am I missing something?

**Comment by Masood10** [comment]
I was using the wrong scope. For reading Tasks you need Group.Read.All, Group.ReadWrite.All scope.
But I am surprised why it doesn't work with all these Tasks.Read Tasks.Read.Shared Tasks.ReadWrite Tasks.ReadWrite.Shared
