### ISSUE TITLE
Azure Web Application Microsoft Graph API Integration / Interoperation

### ISSUE THREAD

**Issue by twcarnahan** [microsoftgraph/aspnet-connect-rest-sample#16]
The application works while in localhost - thank you for the notes and start with Microsoft Graph.
My next issue is getting this on Azure Web Application; of course, there are questions about this like the registration process, scope and authorization of the web application to the API. Can we add a "walkthrough" adding this application to Azure. I ask the question here because this is the only sample I've been able to get to work with Microsoft Graph on the localhost - so I want to publish it to Azure and see if I can get it to work there as an Azure Web Application. Thank you, Tim:

**Comment by DianeD** [comment]
Thanks @twcarnahan . I added a [Deploy the sample to Azure](https://github.com/microsoftgraph/aspnet-connect-rest-sample#deploy-the-sample-to-azure) section to the readme. Please let me know if you have any issues with the process.
Also, you mentioned that you had problems with other Graph samples. Can give some more info? Which did you try and what were the problems?

**Comment by twcarnahan** [comment]
Diane,


This works - however, there are like i mentioned two issues that if you could clarify I would appreciate it.  So, from your readme :

Deploy the sample to Azure

If you have an Azure subscription, you can deploy the sample app to Azure. These instructions assume you've already registered the sample app<https://github.com/microsoftgraph/aspnet-connect-rest-sample#register-the-application> in the Azure Registration Portal.

This is my question/issue: I can't get the application to work if I've registered it with Azure Registration Portal.  FYSA - I've tried added "TenantID: x...x..x...xx to web.config and used my best efforts on permissions - but, no success.

My second issue will be only if it's not answered in the first question --- permissions on the application - how are they setup "correctly"; as I know permissions, AD and as you know it can get messy. I'd like to have a working example.


Diane, thank you much for paying attention to these details as they are very important to us and our customers.

Vr, Tim:

________________________________

**Comment by DianeD** [comment]
Hi Tim. I want to be sure that I understand your situation, so here are some questions/comments to start.

- Where are you having trouble when running the app on Azure? Are you prompted to login/consent at all?
- Are you getting any errors? Sometimes they can show up in the address bar after the login flow.
- This sample uses the Azure AD v2.0 endpoint, so permissions are specified in the app (not in the portal) and then sent to AAD in the **scope** parameter.

**Comment by twcarnahan** [comment]
Diane,


We are "registering our application" in Azure NOT from https://apps.dev.microsoft.com, we run the application from our localhost just as we did before and it fails to report or send back to the reply url. It is set correctly in Azure - but I don't know if this even works?


Do you follow?


Much appreciated ,

Vr, Tim:

________________________________

**Comment by DianeD** [comment]
Hi Tim. I just fixed an incorrect term in the readme (changed "Azure Registration Portal" to "Application Registration Portal"). Sorry! 

You do need to register this sample on https://apps.dev.microsoft.com because that's required for apps that use the Azure AD v2.0 endpoint. The sample won't work if you register it on http://portal.azure.com without some non-trivial code changes.

One difference when using the v2.0 endpoint is how permissions are specified for the app. You don't set them for the registered application in the portal, you send them in an auth request to the Azure AD auth provider. If you inspect the HTTP call, you'll see a **scope** parameter with the permissions. 

This Azure topic provides more details about the new registration portal requirement and how you request permissions: [What's different about the v2.0 endpoint?](https://docs.microsoft.com/en-us/azure/active-directory/active-directory-v2-compare)

Please let me know if this doesn't clarify your questions/issues!

**Comment by twcarnahan** [comment]
Diane,

Oh yes - this is exactly what I'm talking about and have issue with - the links on Azure Registration is great; can there be an example of this or do you know of a working example - as like the small text change you caught, there may be likewise in the other documentation as well so a working example is the best approach if it is available that would give validity to the solution.

Vr, Tim:

________________________________

**Comment by DianeD** [comment]
Hi Tim. I think what you're asking for is a sample that can be registered on http://portal.azure.com with instructions about how to deploy/publish it to an Azure website. 

So I'll update the readme for the [last_v1_auth](https://github.com/microsoftgraph/aspnet-connect-rest-sample/tree/last_v1_auth) version of the ASP.NET Connect sample to include deployment steps and to make sure it matches the new Azure Portal UI. That version uses the Azure AD endpoint (not the Azure AD v2.0 endpoint), so it will only work for work and school accounts. This will still require both registering the app with Azure AD and creating an Azure web app (website).

**Comment by twcarnahan** [comment]
Diane,


I'm trying to get (c.) scenario working --- I've attached the readme file (I marked up from github) as it has good information on permissions - but it doesn't work. Its loads the correct logon page, logs user on and just states in the browser tab "working..."; Scenario (a.) allows the user to consent to permission [and the azure directory has to allow user to do this though an admin can override that setting using your application]. All three below use OWIN - and with the complexities going on here I believe getting (c.) to work could answer some questions. Deployment to Azure information was great and worked but not for (c.) and (c.) doesn't even work with https://localhost:xxxxx/. Also, I don't need the full application of (c.) to work, my interest is with authentication, the using graph to get user profile info such as userprinciplename and be multi-tenited.


Appreciate your help clearing up this problem, Vr Tim:


Scenarios:

a. Your application "aspnet-connect-rest-sample" works,  you register it in apps.dev.microsoft; it even works as or like a "Multi-Tenant" Application.

b. The https://github.com/Azure-Samples/active-directory-dotnet-webapp-openidconnect - works but is "single tenant".

[https://avatars3.githubusercontent.com/u/1844662?v=3&s=400]<https://github.com/Azure-Samples/active-directory-dotnet-webapp-openidconnect>

Azure-Samples/active-directory-dotnet-webapp-openidconnect<https://github.com/Azure-Samples/active-directory-dotnet-webapp-openidconnect>
github.com
active-directory-dotnet-webapp-openidconnect - A .NET MVC web application that uses OpenID Connect to sign-in users from a single Azure Active Directory tenant.



c. The https://github.com/Azure-Samples/active-directory-dotnet-webapp-multitenant-openidconnect.git - does not work.

[https://avatars3.githubusercontent.com/u/1844662?v=3&s=400]<https://github.com/Azure-Samples/active-directory-dotnet-webapp-multitenant-openidconnect.git>

Azure-Samples/active-directory-dotnet-webapp-multitenant-openidconnect<https://github.com/Azure-Samples/active-directory-dotnet-webapp-multitenant-openidconnect.git>
github.com
active-directory-dotnet-webapp-multitenant-openidconnect - A sample .NET 4.5 MVC web app that signs-up and signs-in users from any Azure AD tenant using OpenID Connect.




________________________________

**Comment by DianeD** [comment]
Thanks Tim. I'll take a look at the Azure multitenant sample in scenario (c.). I don't see the readme attachment. Can you please try to attach it again?

**Comment by twcarnahan** [comment]
Diane,


I changed the readme file to a pdf --- maybe that was the problem; as with Multi-Tenant, it is most likely to be a permission issue but again --- I've exhausted my "trial and error" approach. [😊]

Thank you a lot for your patience working with my issue, Tim:

Also note: While your testing, you have to change the "multi tenant" application setting in Azure to "no" in order to delete the application. Really looking forward to this working - thank you again Diane for your knowledge transfer - Tim:

________________________________

**Comment by DianeD** [comment]
Hi Tim. I'm closing this issue and will continue the conversation in [the issue you opened on the Azure sample](https://github.com/Azure-Samples/active-directory-dotnet-webapp-multitenant-openidconnect/issues/20). 

If you added more repro information to the readme you marked up, can you please attach it to that issue?
