### ISSUE TITLE
The solution won't build in Visual studio 2017

### ISSUE THREAD

**Issue by metro-mark** [microsoftgraph/aspnet-connect-rest-sample#26]
I have downloaded the solution and simply try rebuilding it. I have ended up with 44 errors. If your experience is different, please let me know.

**Comment by jamescro** [comment]
I just downloaded the sample and built it in VS 2017 with no errors. Could you pass along the first handful of errors you're getting? Do they have anything to do with NuGet package restore? If that doesn't work, the sample won't build.

**Comment by metro-mark** [comment]
Mainly they have reference not found problems. I have rebuilt the application but did not seem to find the right package for them.
![error](https://user-images.githubusercontent.com/19292407/27096597-6c3f2fe8-5026-11e7-8132-7948d044b045.png)

**Comment by jamescro** [comment]
It looks like you're having a problem with NuGet package restore. Do you have nuget.org set up as a package source in the NuGet package manager? (Go to Tools -> Options and select Nuget Package Manager in the left pane.)

![image](https://user-images.githubusercontent.com/6666618/27099888-2c3e12f0-5031-11e7-998e-68104f3c4e8a.png)

Also, do you have package restore enabled?

![image](https://user-images.githubusercontent.com/6666618/27099908-420c5ab0-5031-11e7-86c4-1cc81cbe8431.png)

**Comment by metro-mark** [comment]
Actually I found out the problem was because there was violation of 260 character limit on the path to the project in the Nuget window. I thought that was fixed on VS2017 but I guess not. I have placed the solution under root and the problem went away.
