### ISSUE TITLE
Server Error in '/' Application.

### ISSUE THREAD

**Issue by ChristofLuytenGFI** [microsoftgraph/aspnet-connect-rest-sample#30]
When I build and run the example, I get the following error in my browser:

![errorscreenshot](https://user-images.githubusercontent.com/32069377/31990893-ad061000-b976-11e7-94e6-f3d466d0fe5e.png)

**Comment by jamescro** [comment]
I'm sorry that you're having this problem with the sample. Could you try going to this page

https://developer.microsoft.com/en-us/graph/quick-start

and running through the ASP.NET MVC quick start? That would give you a similar ASP.NET project.

If you encounter the same error when you try to run it, could you verify that you're not having the same issue that was reported here?

https://social.msdn.microsoft.com/Forums/windows/en-US/cb6a04e1-19d6-4a75-be25-aca16b89f166/server-error-application-httpexception-0x80004005?forum=winformssetup

**Comment by ChristofLuytenGFI** [comment]
Yes, it was the same error. It is solved now. 

Thank you very much.
