### ISSUE TITLE
Sign in does not work.

### ISSUE THREAD

**Issue by SoloRider67** [microsoftgraph/aspnet-connect-rest-sample#31]
I followed the instructions in the Readme. When I click the sign in link, it asks me to sign in but when I get to the home page, my userID is not listed in the nav bar. When I debug, It tells me that the Request.IsAuthenticated is false.

Any suggestions?

**Comment by jamescro** [comment]
Thanks for your feedback. Have you tried running this with a different browser? This looks something that could be caused by a browser setting.

**Comment by SoloRider67** [comment]
Hi James,
THANKS! That was the issue. I feel really stupid now. 

I was using google chrome to as my option to debug in VS2015. When I switched it to IE, there was no issue.  It would be interesting to know why it didn't work in chrome. I don't have any special settings in it. It is a straight install.

This whole AD authentication thing has me confused beyond belief. I normally can figure things out by looking at it. Maybe now that I have this working it will make better sense.

Thanks again for your time.
Ken

**Comment by jamescro** [comment]
Thanks for letting me know. Samples like this exist because authentication is proving to be a challenge for people who want to try Microsoft Graph. Please do let us know if you have any feedback.

**Comment by SoloRider67** [comment]
It's kind of tough since I have been developing for a long time but my applications are behind the times. I am using webforms and all of the examples are MVC so I am fighting 2 things that I don't understand that well.
