### ISSUE TITLE
No alerts

### ISSUE THREAD

**Issue by JGezels** [microsoftgraph/aspnet-connect-rest-sample#34]
Hi
I deployed the application and all looks fine except whatever I do I don't get any alerts.
I noticed that it generates the Graph call so I tried to execute that directly on the graph explorer which also didn't return anything. However, when I tried to do it on the V2/Beta, it returned some info. So my question, why does the application shows the v1.0 query instead of the V2.0?

PS: Do I need to enter a fully qualified domain name?

Thanks

Jan

PS: I removed the username and the tenant id from the PNG file

![graph](https://user-images.githubusercontent.com/28863965/46299300-5a49e980-c5a1-11e8-83d2-0f59d3b8cc1e.png)

**Comment by jasonjoh** [comment]
Did you mean to open this issue on https://github.com/microsoftgraph/aspnet-security-api-sample? Your screenshot is not from this sample.
