### ISSUE TITLE
Rejected emails

### ISSUE THREAD

**Issue by paulewert** [microsoftgraph/aspnet-connect-rest-sample#4]
Why would sending to myself at my onmicrosoft.com email address work, but sending to my GMail address gets rejected as "spam abuse detected"? When I use Office 365 Outlook to send to my GMail account, it goes through with no problem.

**Comment by jamescro** [comment]
Could you supply the email that was filtered and the GMail response to help us look into this?

**Comment by paulewert** [comment]
Dang. It's working today. Funny how software will decide to work when it's facing someone who wrote it. :)

None the less... The email was the default email found in the solution. I didn't touch it. Attached is the diagnostic info from the rejection message (sans personal info):

[diagnostic.txt](https://github.com/OfficeDev/O365-AspNetMVC-Microsoft-Graph-Connect/files/105841/diagnostic.txt)
.
