### ISSUE TITLE
Multi-Tenant support  

### ISSUE THREAD

**Issue by shyambhiogade** [microsoftgraph/aspnet-connect-rest-sample#8]
Hi, 
how to make this application work with the multi tenant. I selected the Multitenant option in manage azure portal for this app, just as try but that did not worked. there are other sample application which demo about multi-tenant but i could not understood it properly..

how to make this app multitenant

**Comment by jamescro** [comment]
Have you seen the instructions on this page? 
https://github.com/microsoftgraph/php-connect-rest-sample/wiki/How-to:-Make-my-Azure-web-application-multi-tenant
It could be that your App ID URI isn't a verified custom domain.

**Comment by shyambhiogade** [comment]
thanks james, it worked :+1:  wish you a very good day ahead..

**Comment by jamescro** [comment]
I'm glad it worked. Thanks for following up.

**Comment by shyambhiogade** [comment]
i think you should also mention somewhere that this app supports multitenant and some instruction about it, i have found few application about the multitenant but they were little complicated..https://github.com/OfficeDev/O365-WebApp-MultiTenant and this https://github.com/Azure-Samples/active-directory-dotnet-webapp-multitenant-openidconnect
